### ISSUE TITLE
Version number is hardcoded in the Click decorator notation

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/supervisor-frontend-service#92]
This should instead make use of the version information provided in the `__init__.py` file.

If you are using PyCharm, you would want to do `Ctrl`+`Shift`+`F` to search for occurrences of this hardcoded version across multiple files.

![image](https://user-images.githubusercontent.com/49605954/118080166-44e30000-b3d7-11eb-8d2a-ba501dbbd6d2.png)

**Comment by sachindavra** [comment]
Hi @t0xic0der, I would like to contribute if you could help on this. 
> Could you let me know the file where this has to be changed. 

I would like to read it. 

PS: I am new to open source.

**Comment by t0xic0der** [comment]
There's this file called `main.py` located inside `src/svfrontend` directory, where the line number 424 is **hardcoded** to have the aforementioned version number. That needs to be **replaced** with a version number picked from a file called `__init__.py` located inside `src/frontend` directory.

Let me know if you need any more help on this. If you are up for this task, I will assign you this issue. :)

**Comment by sachindavra** [comment]
Kindly assign this to me. 
I would reach out to you if need guidance. 
Thanks.

**Comment by t0xic0der** [comment]
Cool. I am assigning this issue to you. :)
