### ISSUE TITLE
HTTP Resp 500 function has been incorrectly named

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/supervisor-frontend-service#93]
At line number 78, it should be `e500page` instead of `e403page`.

![image](https://user-images.githubusercontent.com/49605954/118082230-6abdd400-b3da-11eb-93a1-01c09d14724f.png)

**Comment by sachindavra** [comment]
Hi @t0xic0der, I am new to open-source and want to contribute to this project.
Could you assign this to me?

**Comment by t0xic0der** [comment]
Sure @sachindavra. I am assigning this to you. :)
